# Generated by Django 6.0.3 on 2026-05-09 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=255)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('expires_at', models.BigIntegerField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('id_token', models.TextField(blank=True, default='')),
                ('session_state', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'provider_account_id')},
            },
        ),
    ]
