# Generated by Django 6.0.3 on 2026-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_project_achievement_event_skill_task_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dfa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='validate_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
