# Generated by Django 6.0.3 on 2026-05-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_user_dfa_user_validate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dfa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='validate_code',
        ),
    ]
